name: Run ikanhanman

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python run.py

      - name: Upload output.txt
        uses: actions/upload-artifact@v2
        with:
          name: 爱看韩漫
          path: 爱看韩漫.json
          retention-days: 90